export const HOLDER = "HOLDER-POLDER";
export const DEFAULT_FONT = "Helvetica";

export const autoFillingRequiredFields = {
  sideNumberFontSize: "12",
  sideNumberFontColor: "FFF",
  sideNumberFillingColor: "1E88E5",
  sideNumberWidth: "20",
  sideNumberRadius: "10",
  fontSize: "12",
  fontColor: "000",
  marginTop: "6",
  marginBottom: "6",
  firstRowIndent: "0",
  otherRowsIndent: "0",
  wordSpacing: "0",   
  borderColor: "f00",
  borderThickness: "2",
};

export const emptyDecFormState = {
  decKey: "",
  group: "",
  groupToCreate: "",
  active: false,
  decNameEn: "",
  decNameDe: "",
  decNameRu: "",
  decNameFr: "",
  decNameFrCa: "",
  decNameEs: "",
  wordStyleName: "",
  softReturn: false,
  indentationalLevel: "",
  backspaceActionWithContent: "merge",
  backspaceActionWithContentStyle: "default",
  returnActionNextSection: "default",
  returnActionEmptySection: "default",
  tabAction: "",
  shiftTabAction: "",
  isList: false,
  listName: HOLDER,
  orderLevel: "",
  prefix: "",
  suffix: "",
  suffixDistance: "0.25",
  magicTabs: false,
  listType: "unordered",
  listItem: "bulletpoint",
  unicodeNumber: "",
  unicodeChar: "",
  numberingStyle: "decimal",
  continueNumbering: false,
  allowRestartNumbering: false,
  includePreviousFrom: "",
  sideNumber: false,
  sideNumberFont: DEFAULT_FONT,
  customSideNumberFont: "",
  sideNumberAlignment: "center",
  referenceGroup: "",
  referenceGroupToCreate: "",
  font: DEFAULT_FONT,
  customFont: "",
  alignment: "left",
  fontColorName: "Black",
  bold: false,
  italic: false,
  underlined: false,
  stroke: false,
  textTransform: "none",
  verticalAlign: "baseline",
  lineSpacing: "1.15",
  customLineSpacing: "",
  leftBorder: false,
  rightBorder: false,
  topBorder: false,
  bottomBorder: false,
  borderColorName: "Red",
  borderType: "solid",
  borderConnectToPrevious: false,
  fillingColorName: "",
  fillingColor: "",
  fillingfillingConnectToPrevious: false,
  tocIndentation: "",
  shortCutWin: "",
  shortCutWinView: "",
  shortCutMac: "",
  shortCutMacView: "",
  ...autoFillingRequiredFields,
};