const decToSendDefaultProps = {
    item_type: "style",
    style_properties: {},
    keyboard_shortcut: {},
    xref_target_type_group_key: null,
    is_possible_xref_target: false,
    show_in_editor_toc: false,
    editor_toc_indentation: null,
    editor_toc_filter_level: null,
    list_key: null,
    item_order: null,
    extra_hanging_indentation: null,
    extra_hanging_indentation_at_grid: false,
    numerated_list_format: null,
    numerated_list_start: null,
    numerated_list_pattern: null,
    numerated_list_style: "",
    is_auto_restart_numbering: false,
    allow_restart_numbering: false,
    bullet_list_format: null,
    movable: true,
    content_required: false,
    on_return_style_key: null,
    on_return_indentation: null,
    item_order_allow_tab: false,
};

export default decToSendDefaultProps;