import decoratorsList from "./decoratorsList";
import fontSet from "./fontsSet";
import { LANGS, MAIN_LANG_KEY, ADDITIONAL_LANGS } from "./localeConstants";
import { tabsErrorInitialState, sectionsTabNumbers } from "./validationData";
import {
    alignmentList,
    backSpaceActionsMap,
    bulletNamesMap,
    orderedListStylesMap,
    numberingSets,
    sectionTypesMap,
    sampleText,
} from "./constants";
import { 
    initialFormState, 
    autoFillingRequiredFields, 
    HOLDER,
    GLOBAL_FALLBACK_MARK,
    DEFAULT_FONT,
    DEFAULT_FONT_SIZE,
    DEFAULT_SIDE_NUMBER_FONT_COLOR,
    DEFAULT_SIDE_NUMBER_FILLING_COLOR,
    DEFAULT_SIDE_NUMBER_WIDTH,
    DEFAULT_SIDE_NUMBER_RADIUS,
    DEFAULT_FONT_COLOR,
    DEFAULT_ROW_INDENT,
    DEFAULT_MARGIN,
    DEFAULT_WORD_SPACING,
    DEFAULT_LINE_SPACING,
    DEFAULT_BORDER_COLOR,
    DEFAULT_BORDER_THICKNESS,
} from "./initialFormState";

export {
    decoratorsList,
    alignmentList,
    backSpaceActionsMap,
    bulletNamesMap,
    orderedListStylesMap,
    numberingSets,
    tabsErrorInitialState,
    sectionsTabNumbers,
    sectionTypesMap,
    sampleText,
    fontSet,
    initialFormState, 
    autoFillingRequiredFields, 
    HOLDER,
    GLOBAL_FALLBACK_MARK,
    DEFAULT_FONT,
    DEFAULT_FONT_SIZE,
    DEFAULT_SIDE_NUMBER_FONT_COLOR,
    DEFAULT_SIDE_NUMBER_FILLING_COLOR,
    DEFAULT_SIDE_NUMBER_WIDTH,
    DEFAULT_SIDE_NUMBER_RADIUS,
    DEFAULT_FONT_COLOR,
    DEFAULT_ROW_INDENT,
    DEFAULT_MARGIN,
    DEFAULT_WORD_SPACING,
    DEFAULT_LINE_SPACING,
    DEFAULT_BORDER_COLOR,
    DEFAULT_BORDER_THICKNESS,
    LANGS,
    MAIN_LANG_KEY,
    ADDITIONAL_LANGS,
};