import DecDataConverter from "./DecDataConverter";
import getShortCutUtils from "./getShortCutUtils";
import isFontAvailable from "./isFontAvailable";
import prepareColorCode from "./prepareColorCode";
import { 
    getErrorState, 
    getTabNumberToSwitch,
    checkNames,
    checkDecKey,
    checkListName,
 } from "./validationFunctions";
import {
    getCorrectColor,
    selectAllOnClick,
    getOffset,
    getPreviewFont,
    getUnstyledText,
    unicodeNumberToChar,
    unicodeCharToNumber,
    scrollToBottom,
    changeAndScroll,
    selectAllEditableContent,
    getListChars,
    detectOS,
    fillMissedFields,
    focusInput,
    focusOnEmptyField,
    trimOnTextFieldBlur,
    filterKeyInput,
    snakeCaseOnTextFieldBlur,
} from "./helpers.js";

export {
    DecDataConverter,
    getShortCutUtils,
    isFontAvailable,
    prepareColorCode,
    getErrorState,
    getTabNumberToSwitch,
    checkNames,
    checkDecKey,
    checkListName,
    getCorrectColor,
    getPreviewFont,
    selectAllOnClick,
    getOffset,
    getUnstyledText,
    unicodeNumberToChar,
    unicodeCharToNumber,
    scrollToBottom,
    changeAndScroll,
    selectAllEditableContent,
    getListChars,
    detectOS,
    fillMissedFields,
    focusInput,
    focusOnEmptyField,
    trimOnTextFieldBlur,
    filterKeyInput,
    snakeCaseOnTextFieldBlur,
};